# STAC Connection information
[catalog]
name = "Digital Earth Australia"
url = "https://explorer.sandbox.dea.ga.gov.au/stac"

[catalog.rio_config]
cloud_defaults = true
aws = { aws_unsigned = true }
AWS_S3_ENDPOINT = "s3.ap-southeast-2.amazonaws.com"

# Sentinel-2a Product Definition
[collections.ga_s2am_ard_3]
description = "Sentinel-2a"

# band aliases 
[collections.ga_s2am_ard_3.aliases]
costal_aerosol = "nbart_coastal_aerosol"
blue = "nbart_blue"
green = "nbart_green"
red = "nbart_red"
red_edge_1 = "nbart_red_edge_1"
red_edge_2 = "nbart_red_edge_2"
red_edge_3 = "nbart_red_edge_3"
nir = "nbart_nir_1"
nir_narrow = "nbart_nir_2"
swir_1 = "nbart_swir_2"
swir_2 = "nbart_swir_3"
fmask = "oa_fmask"
s2cloudless = "oa_s2cloudless_mask"

# List default metadata attributes for all assets
[collections.ga_s2am_ard_3.assets."*"]
data_type = "int16"
nodata = -999
unit = "1"

# Overwrite metadata for oa_fmask
[collections.ga_s2am_ard_3.assets.oa_fmask]
data_type = "uint8"
nodata = 0
unit = "1"

# Overwrite metadata for oa_s2cloudless_mask
[collections.ga_s2am_ard_3.assets.oa_s2cloudless_mask]
data_type = "uint8"
nodata = 0
unit = "1"

# Set up all ga_s2am_ard_3 masks
[collections.ga_s2am_ard_3.masks]

# Set up oa_fmask config
[collections.ga_s2am_ard_3.masks.oa_fmask]
alias = "fmask"
description = "Function of mask"
type = "categorical"
categories_to_mask = ["nodata", "cloud", "shadow", "snow", "water"]
flags_definition.bits = [0, 1, 2, 3, 4, 5, 6, 7]

[collections.ga_s2am_ard_3.masks.oa_fmask.flags_definition.values]
"nodata" = 0
"valid" = 1
"cloud" = 2
"shadow" = 3
"snow" = 4
"water" = 5

# Set up oa_s2cloudless_mask config
[collections.ga_s2am_ard_3.masks.oa_s2cloudless_mask]
alias = "s2cloudless"
description = "S2 Cloudless Mask"
type = "categorical"
categories_to_mask = ["nodata", "cloud"]
flags_definition.bits = [0, 1, 2]

[collections.ga_s2am_ard_3.masks.oa_s2cloudless_mask.flags_definition.values]
"nodata" = 0
"valid" = 1
"cloud" = 2

# Sentinel-2b Product Definition
[collections.ga_s2bm_ard_3]
description = "Sentinel-2b"

# Band aliases
[collections.ga_s2bm_ard_3.aliases]
costal_aerosol = "nbart_coastal_aerosol"
blue = "nbart_blue"
green = "nbart_green"
red = "nbart_red"
red_edge_1 = "nbart_red_edge_1"
red_edge_2 = "nbart_red_edge_2"
red_edge_3 = "nbart_red_edge_3"
nir = "nbart_nir_1"
nir_narrow = "nbart_nir_2"
swir_1 = "nbart_swir_2"
swir_2 = "nbart_swir_3"
fmask = "oa_fmask"
s2cloudless = "oa_s2cloudless_mask"

# List default metadata attributes for all assets 
[collections.ga_s2bm_ard_3.assets."*"]
data_type = "int16"
nodata = -999
unit = "1"

# Overwrite metadata for oa_fmask
[collections.ga_s2bm_ard_3.assets.oa_fmask]
data_type = "uint8"
nodata = 0
unit = "1"

# Overwrite metadata for oa_s2cloudless_mask
[collections.ga_s2bm_ard_3.assets.oa_s2cloudless_mask]
data_type = "uint8"
nodata = 0
unit = "1"

# Set up masks
[collections.ga_s2bm_ard_3.masks]

# Set up oa_fmask config
[collections.ga_s2bm_ard_3.masks.oa_fmask]
alias = "fmask"
description = "Function of mask"
type = "categorical"
categories_to_mask = ["nodata", "cloud", "shadow", "snow", "water"]
flags_definition.bits = [0, 1, 2, 3, 4, 5, 6, 7]

[collections.ga_s2bm_ard_3.masks.oa_fmask.flags_definition.values]
"nodata" = 0
"valid" = 1
"cloud" = 2
"shadow" = 3
"snow" = 4
"water" = 5

# Set up oa_s2cloudless_mask config
[collections.ga_s2bm_ard_3.masks.oa_s2cloudless_mask]
alias = "s2cloudless"
description = "S2 Cloudless Mask"
type = "categorical"
categories_to_mask = ["nodata", "cloud"]
flags_definition.bits = [0, 1, 2]

[collections.ga_s2bm_ard_3.masks.oa_s2cloudless_mask.flags_definition.values]
"nodata" = 0
"valid" = 1
"cloud" = 2

# Collection
[collections.ga_ls_wo_fq_cyear_3]
description = "Geoscience Australia Landsat Water Observations Frequency Calendar Year Collection 3"

#Start with aliases for bands
[collections.ga_ls_wo_fq_cyear_3.aliases]
count_wet = "count_wet"
count_clear = "count_clear"
frequency = "frequency"

# List default metadata attributes for all assets
[collections.ga_ls_wo_fq_cyear_3.assets."*"]
data_type = "int16"
nodata = -999
unit = "1"

# Overwrite metadata for any unique bands
[collections.ga_ls_wo_fq_cyear_3.assets.frequency]
data_type = "float32"
nodata = "NaN"
unit = "1"

# Landsat-8-9 yearly geomedian Product Definition
[collections.ga_ls8cls9c_gm_cyear_3]
description = "Landsat-8&9 yearly geomedian"

# Band aliases
[collections.ga_ls8cls9c_gm_cyear_3.aliases]
blue = "nbart_blue"
green = "nbart_green"
red = "nbart_red"
nir = "nbart_nir"
swir_1 = "nbart_swir_1"
swir_2 = "nbart_swir_2"

# List metadata attributes for spectral bands
# TODO: add metadata for dev bands
[collections.ga_ls8cls9c_gm_cyear_3.assets."*"]
data_type = "int16"
nodata = -999
unit = "1"

# Sentinel-2 Barest Earth Product Definition
[collections.s2_barest_earth]
description = "Sentinel-2 Barest Earth"

# List metadata attributes for spectral bands
[collections.s2_barest_earth.assets."*"]
data_type = "int16"
nodata = -999
unit = "1"

# Band aliases
[collections.s2_barest_earth.aliases]
blue = "s2be_blue"
green = "s2be_green"
red = "s2be_red"
red_edge_1 = "s2be_red_edge_1"
red_edge_2 = "s2be_red_edge_2"
red_edge_3 = "s2be_red_edge_3"
nir = "s2be_nir_1"
nir_2 = "s2be_nir_2"
swir_1 = "s2be_swir_2"
swir_2 = "s2be_swir_3"

# SRTM DEM product Definition
[collections.ga_srtm_dem1sv1_0]
description = "Geoscience Australia SRTM 1 second DEM version 1.0"

# List metadata attributes
[collections.ga_srtm_dem1sv1_0.assets."*"]
data_type = "float32"
nodata = -340282346638528859811704183484516925440.0
unit = "metre"

# Multiscale topographic position image product Definition
[collections.multi_scale_topographic_position]
description = "Multiscale topographic position image"

# List metadata attributes
[collections.multi_scale_topographic_position.assets."*"]
data_type = "int16"
nodata = 0
unit = "0.0039"

# Weathering Intensity product Definition
[collections.weathering_intensity]
description = "Weathering Intensity"

# List metadata attributes
[collections.weathering_intensity.assets."*"]
data_type = "float32"
nodata = -1.0
unit = "0.16666666666666666"